### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Czarified** [heczis/pybeam#8]
What is the intended license for this Library? I do not see anything on the main page, and none was selected in the project properties.

**Comment by heczis** [comment]
Hi, Czarified,
thanks for pointing that out. I chose the MIT license since it seems to be quite permissive.
Commit [b310166](https://github.com/heczis/pybeam/commit/b31016697f70addaa7e45cd2833d0b3bc51d2cab) thus closes this issue.
